package com.pkoding.recognizer.lexer;

public enum TokenType {
	
	VARIABLE, FUNCTION_NAME, KEYWORD, OTHER, NEWLINE, FUNCTION_DECL, CLASS_DECL, CONTROL_BEGIN, END, VAR_DECL, 
	VAR_UPDATE, OP_PAREN, CL_PAREN, SEMI_COLON, FOR, IF, ELSE_IF, ELSE, TRY, CATCH, WHILE, FINALLY, SWITCH, 
	DO, THEN, AUTO_STRING, ARRAY_LIT, STRING, EOF, ASSERT, NEW, CLASS_NAME, BITWISE_NOT, MINUS, PLUS, 
	NEGATIVE, POSITIVE, BITWISE_AND, BITWISE_OR, BITWISE_XOR, CONCAT, NOT, AND, OR, TRUE, FALSE, NUMBER, EQ, 
	NEQ, IN, ARRAY_ELEMENT, EMPTY_STRING, GT, GEQ, LT, LEQ, IDT, NIDT, TIMES, MODULUS, OVER, NULL, COMMA, 
	BREAK, CONTINUE, RETURN, EMPTY_ARRAY, LOOP, VISIBILITY

}
